<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
You are registered viewer!
<form action="/login" method="post">
    Введите email: <input type="email" name="username"><br>
    Введите пароль: <input type="password" name="password"><br>
    <input type="submit" value="Войти"/>
</form>

<a href="/registration">Зарегистрироваться</a>
</body>
</html>